/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewRouteRouteImport } from './routes/new/route'
import { Route as SignInRouteImport } from './routes/signIn'
import { Route as NewIndexRouteImport } from './routes/new/index'
import { Route as NewCompletionRouteImport } from './routes/new/completion'
import { Route as NewMasterRouteImport } from './routes/new/master'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRouteRoute = NewRouteRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/signIn',
  path: '/signIn',
  getParentRoute: () => rootRouteImport,
} as any)
const NewIndexRoute = NewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NewRouteRoute,
} as any)
const NewCompletionRoute = NewCompletionRouteImport.update({
  id: '/completion',
  path: '/completion',
  getParentRoute: () => NewRouteRoute,
} as any)
const NewMasterRoute = NewMasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => NewRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new': typeof NewRouteRouteWithChildren
  '/signIn': typeof SignInRoute
  '/new/completion': typeof NewCompletionRoute
  '/new/master': typeof NewMasterRoute
  '/new/': typeof NewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signIn': typeof SignInRoute
  '/new/completion': typeof NewCompletionRoute
  '/new/master': typeof NewMasterRoute
  '/new': typeof NewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/new': typeof NewRouteRouteWithChildren
  '/signIn': typeof SignInRoute
  '/new/completion': typeof NewCompletionRoute
  '/new/master': typeof NewMasterRoute
  '/new/': typeof NewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/new' | '/signIn' | '/new/completion' | '/new/master' | '/new/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/signIn' | '/new/completion' | '/new/master' | '/new'
  id:
    | '__root__'
    | '/'
    | '/new'
    | '/signIn'
    | '/new/completion'
    | '/new/master'
    | '/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewRouteRoute: typeof NewRouteRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signIn': {
      id: '/signIn'
      path: '/signIn'
      fullPath: '/signIn'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new/': {
      id: '/new/'
      path: '/'
      fullPath: '/new/'
      preLoaderRoute: typeof NewIndexRouteImport
      parentRoute: typeof NewRouteRoute
    }
    '/new/completion': {
      id: '/new/completion'
      path: '/completion'
      fullPath: '/new/completion'
      preLoaderRoute: typeof NewCompletionRouteImport
      parentRoute: typeof NewRouteRoute
    }
    '/new/master': {
      id: '/new/master'
      path: '/master'
      fullPath: '/new/master'
      preLoaderRoute: typeof NewMasterRouteImport
      parentRoute: typeof NewRouteRoute
    }
  }
}

interface NewRouteRouteChildren {
  NewCompletionRoute: typeof NewCompletionRoute
  NewMasterRoute: typeof NewMasterRoute
  NewIndexRoute: typeof NewIndexRoute
}

const NewRouteRouteChildren: NewRouteRouteChildren = {
  NewCompletionRoute: NewCompletionRoute,
  NewMasterRoute: NewMasterRoute,
  NewIndexRoute: NewIndexRoute,
}

const NewRouteRouteWithChildren = NewRouteRoute._addFileChildren(
  NewRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewRouteRoute: NewRouteRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
