/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as OnboardingMasterIndexRouteImport } from './routes/onboarding/master/index'
import { Route as OnboardingStaffIndexRouteImport } from './routes/onboarding/staff/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingMasterIndexRoute = OnboardingMasterIndexRouteImport.update({
  id: '/onboarding/master/',
  path: '/onboarding/master/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStaffIndexRoute = OnboardingStaffIndexRouteImport.update({
  id: '/onboarding/staff/',
  path: '/onboarding/staff/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/onboarding/master/': typeof OnboardingMasterIndexRoute
  '/onboarding/staff/': typeof OnboardingStaffIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/onboarding/master': typeof OnboardingMasterIndexRoute
  '/onboarding/staff': typeof OnboardingStaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/onboarding/master/': typeof OnboardingMasterIndexRoute
  '/onboarding/staff/': typeof OnboardingStaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/onboarding/' | '/onboarding/master/' | '/onboarding/staff/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/onboarding' | '/onboarding/master' | '/onboarding/staff'
  id:
    | '__root__'
    | '/'
    | '/onboarding/'
    | '/onboarding/master/'
    | '/onboarding/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  OnboardingMasterIndexRoute: typeof OnboardingMasterIndexRoute
  OnboardingStaffIndexRoute: typeof OnboardingStaffIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/master/': {
      id: '/onboarding/master/'
      path: '/onboarding/master'
      fullPath: '/onboarding/master/'
      preLoaderRoute: typeof OnboardingMasterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/staff/': {
      id: '/onboarding/staff/'
      path: '/onboarding/staff'
      fullPath: '/onboarding/staff/'
      preLoaderRoute: typeof OnboardingStaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
  OnboardingMasterIndexRoute: OnboardingMasterIndexRoute,
  OnboardingStaffIndexRoute: OnboardingStaffIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
